### ISSUE TITLE
Make use of information passed from login screen

### ISSUE THREAD

**Issue by codethecoffee** [eecs330-section69-askisers/askisers-react#9]
Right now, the name that the user inputs into the login screen is passed to the Dashboard component as props. `{this.props.name} `isn't actually used for anything on the Dashboard right now; I just put a `console.log` in the `render` method as a sanity check to demonstrate that the data is passing through properly. 

@Faraaz-Beyabani Should we implement a "User Profile" tab in the dashboard that shows all of your account information?

**Comment by Faraaz-Beyabani** [comment]
Yup, that's a good idea which probably necessitates adding a top nav bar with a tab for questions too?

Also an easy thing to do is probably to personalize the welcome message when no question is selected.

**Comment by codethecoffee** [comment]
Implemented by adding a profile sidebar
